export const ADD_IMAGE = ADD_IMAGE
export const RATE_IMAGE = RATE_IMAGE



export const DEFAULT_GALLERY_IMAGE_WIDTH = 220
export const DEFAULT_GALLERY_IMAGE_HEIGHT = 220

export const DEFAULT_GALLERY_ROW_COUNT = 12
export const DEFAULT_GALLERY_COLUMN_COUNT = 3
export const DEFAULT_COLUMN_ROW_SIZE = Math.floor(DEFAULT_GALLERY_ROW_COUNT / DEFAULT_GALLERY_COLUMN_COUNT)

export const DEFAULT_START_COUNT = 5
