export const ADD_IMAGE = 'ADD_IMAGE'
export const UPDATE_IMAGE = 'UPDATE_IMAGE'
export const DELETE_IMAGE = 'DELETE_IMAGE'
export const RECIEVE_IMAGES = 'RECIEVE_IMAGES'


export const REQUEST_IMAGES = 'REQUEST_IMAGES'
export const REQUEST_IMAGE = 'REQUEST_IMAGE'
export const REQUEST_IMAGE_UPDATE = 'REQUEST_IMAGE_UPDATE'

export const RESET_FETCH = 'RESET_FETCH'


export const DEFAULT_GALLERY_IMAGE_WIDTH = 220
export const DEFAULT_GALLERY_IMAGE_HEIGHT = 220

export const DEFAULT_GALLERY_ROW_COUNT = 12
export const DEFAULT_GALLERY_COLUMN_COUNT = 3
export const DEFAULT_COLUMN_ROW_SIZE = Math.floor(DEFAULT_GALLERY_ROW_COUNT / DEFAULT_GALLERY_COLUMN_COUNT)

export const DEFAULT_START_COUNT = 5
