export const ADD_IMAGE = ADD_IMAGE
export const RATE_IMAGE = RATE_IMAGE



export const DEFAULT_GALLERY_IMAGE_WIDTH = 200
export const DEFAULT_GALLERY_IMAGE_HEIGHT = 200
export const DEFAULT_GALLERY_COLUMN = 4
